<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo</name>
   <tag></tag>
   <elementGuidId>36b8fd85-5fdd-48d9-a2ff-2764d0b3c188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.login_logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.login_logo</value>
      <webElementGuid>8ce3289f-ffb8-434c-9344-c8131f9217a1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
