<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cart</name>
   <tag></tag>
   <elementGuidId>07621492-d34d-4bf4-aa65-dea1de94623b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.shopping_cart_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.shopping_cart_link</value>
      <webElementGuid>995a094f-6128-497a-8410-f18e86540694</webElementGuid>
   </webElementProperties>
</WebElementEntity>
