<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>complete-order</name>
   <tag></tag>
   <elementGuidId>9f067255-a162-4dad-a354-fbd63831cc15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.complete-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.complete-header</value>
      <webElementGuid>c2bdb8f5-ae2d-4c9b-b905-4153efe95661</webElementGuid>
   </webElementProperties>
</WebElementEntity>
